# Generated by Django 5.0.6 on 2024-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customeuser_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='DOB',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
