# Generated by Django 5.0.6 on 2024-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customeuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='AdharNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Pancardno',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='Phonenumber',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
