# Generated by Django 5.0.6 on 2024-06-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customeuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
